# Generated by Django 5.2.3 on 2025-07-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='service_expiration',
            new_name='birth_date',
        ),
    ]
