# Generated by Django 5.2.3 on 2025-07-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_rename_service_expiration_customer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_sms_provider',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sms_address',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sms_password',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sms_token',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sms_user',
            field=models.CharField(null=True),
        ),
    ]
