# Generated by Django 5.2.3 on 2025-07-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_remove_company_custom_sms_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sms_credit',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.company')),
            ],
        ),
    ]
