# Generated by Django 5.2.3 on 2025-07-18 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_company_sms_credit_smslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_last4', models.CharField(max_length=4)),
                ('amount', models.PositiveIntegerField()),
                ('tracking_code', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.company')),
            ],
        ),
    ]
